### ISSUE TITLE
Mobile Aside menu requires 2 clicks to navigate

### ISSUE THREAD

**Issue by Spacarar** [vikdiesel/admin-one-vue-bulma-dashboard#7]
When navigating using the mobile aside menu on an actual device (emulating mobile on browsers did not have this issue) it takes two clicks(taps) to navigate to the desired page. 

Shown below is after initial open of the sidebar the active link is highlighted as expected.
![open](https://user-images.githubusercontent.com/24302366/70099357-dac40a00-15eb-11ea-8699-9d53c1391390.PNG)

Then after the first press the second menu item is also highlighted but nothing is navigated to and the aside menu remains open. Sometimes you can get around it by holding the menu item down for a second or pressing a bit harder, but on a quick tap it does not navigate.
![double](https://user-images.githubusercontent.com/24302366/70099359-db5ca080-15eb-11ea-864b-e947d8065989.PNG)

not sure if this is intentional or if there is an easy way around this, but I didn't see anything that should be blocking the ui from navigating on the first press so I was hoping you would be able to help figure this out.

**Comment by mgd722** [comment]
same issue. any insight, @vikdiesel ?

**Comment by vikdiesel** [comment]
hi, thanks for pointing out. That's feature of Safari (mobile version).

Safari treats first tap as `hover`, and second tap as `click`, but only when there's something to display on `hover`. For instance, when `hover` brings some custom tooltip element.

I have an insight, but a bit hacky: in earlier versions of Admin One I've been forcing `this.$router.push()` on mobile touch events. Current version doesn't have this, because in earlier versions there were custom tooltips, which were triggered on hover event.

Do you experience the same behavior on [Admin One's demo page](https://admin-one-free.justboil.me/)?

**Comment by Spacarar** [comment]
It appears that this issue is not present on the demo page. Thank you for the insights. How did you accomplish forcing this action on mobile touch events?

**Comment by vikdiesel** [comment]
I've been using https://github.com/jerrybendy/vue-touch-events which gives you `v-touch` directive where you can call `this.$router.push(yourDestination)`

**Comment by Spacarar** [comment]
cool, well we shall do the same in our project as well then. Thanks for the help/information and thanks for the awesome template! closing the issue.
